WINDOW_WIDTH = 1300# 1920
WINDOW_HEIGHT = 880 # 1080

# enemies health
PLAYER_HEALTH = 100
SLIME_HEALTH = 30
SKELETON_HEALTH = 50 
ZOMBIE_HEALTH = 65

# enemies damage
SLIME_DAMAGE = 5
SKELETON_DAMAGE = 8 
ZOMBIE_DAMAGE = 10

# cooldown after player takes damage
INVULN_TIME = 0.3

# animation speed
PLAYER_ANIMATION_SPEED = 0.12

# sprites sizes
PLAYER_WIDTH = 80
PLAYER_HEIGHT = 110
